version: '3.8'
name: inception

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "443:443"
    restart: always
    networks:
      - my-network
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    networks:
      - my-network
    volumes:
      - wordpress_data:/usr/share/webapps
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    networks:
      - my-network
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
    name: wordpress_webpage
  db_data:
    name: wordpress_database
    driver: local

networks:
  my-network:
    driver: bridge
