version: '3.8'
name: inception

services:
  nginx:
    container_name: nginx
    build: # Defines the path for the Dockerfile & other files
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    env_file: # Enviroment variables given to the container
      - .env
    ports: # Ports accessible outside the container
      - "443:443"
    restart: always # Will restart if any error is encountered
    networks: # Will be part of a network ( to be able to exchange data with Wordpress )
      - my-network
    depends_on: # The container will start after Wordpress container is up
      - wordpress
  wordpress:
    container_name: wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    networks:
      - my-network
    volumes: # Defines what volume it will use & the path to be linked with in the container
      - wordpress_data:/var/www/wordpress
  mariadb:
    container_name: mariadb
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    networks:
      - my-network
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data: # Stores Wordpress & Static website files
    name: wordpress_webpage
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jaizpuru/data/wordpress_webpage
  db_data: # Stores the linked database with Wordpress
    name: wordpress_database
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jaizpuru/data/wordpress_database

networks:
  my-network:
    driver: bridge
    driver_opts:
      type: none
      device: ~/data
      o: bind
