version: '3'
name: inception

services:
  nginx:
    image: nginx
    build:
      context: ./srcs/nginx/
      dockerfile: Dockerfile
    env_file:
      - srcs/.env
    ports:
      - "443:443"
    restart: always
    networks:
      - my-network
    depends_on:
      - wordpress

  wordpress:
    image: wordpress
    env_file:
      - srcs/.env
    build:
      context: ./srcs/wordpress
      dockerfile: Dockerfile
    restart: always
    networks:
      - my-network
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html

  mariadb:
    image: mariadb
    build:
      context: ./srcs/mariadb
      dockerfile: Dockerfile
    env_file:
      - srcs/.env
    restart: always
    networks:
      - my-network
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
    driver: local

networks:
  my-network:
    driver: bridge
